name: Build

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 23 * * *'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: download
      run: |
        sudo apt update
        sudo apt -y install jq
        crowdin_url="https://api.crowdin.com/api/v2/projects/${{secrets.CROWDIN_PROJECT_ID}}/translations/exports"
        echo "$crowdin_url"
        download_url=`curl -X POST "$crowdin_url" -d '{"targetLanguageId":"en","format": "android","fileIds": [17566]}' -H "Authorization: Bearer ${{secrets.CROWDIN_PERSONAL_TOKEN}}" -H "Content-Type: application/json" | jq -r .data.url`
        curl -L "$download_url" -o "sources/AdGuard Applications.xml"
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Update Translate"
        git push
